image: Visual Studio 2017
configuration: Release

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

before_build:
  - appveyor DownloadFile https://download.microsoft.com/download/5/A/8/5A8B8314-CA70-4225-9AF0-9E957C9771F7/vs_BuildTools.exe
  # - cmd: git clone --recursive -j8 https://github.com/sgeto/wireshark.git
  # - cmd: cd wireshark
  # - cmd: git remote add upstream https://github.com/wireshark/wireshark.git
  # - cmd: git fetch upstream
  - cmd: echo %cd% && md %cd%\VS_BuildTools2017_offline
  - cmd: vs_BuildTools.exe --layout c:\VS_BuildTools2017_offline --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --lang en-US
build_script:
# https://stackoverflow.com/questions/22680954/7zip-ultra-lzma2-compression
# https://superuser.com/questions/281573/what-are-the-best-options-to-use-when-compressing-files-using-7-zip
# To create the smallest standard ZIP file that 7-Zip can create, try:
# 7z a -mm=Deflate -mfb=258 -mpass=15 -r foo.zip C:\Path\To\Files\*
# Otherwise if you're not care about ZIP standard, use the following ultra settings:
# XXX - try lzma2 or PPMD and compare sizes:
# lzma = 470
# PPMD = 490
# "I regularly compress server/text logs (60MB+) using these options and they usually come out at 1-2% of the original size. For text such as log files, ppmd is definitely the way to go."
  # - cmd: 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on wireshark.7z wireshark
  # - cmd: 7z a -t7z -m0=PPMD -mx=9 -ms=on wireshark.7z wireshark
  - cmd: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on VS_BuildTools2017_offline.7z VS_BuildTools2017_offline

after_build:
  - cmd: dir
artifacts:
  - path: '**\*.7z'
  - path: '**\*.zip'
  - path: VS_BuildTools2017_offline.7z
deploy: off