install:
- appveyor DownloadFile https://nmap.org/npcap/dist/latest-npcap-installer.exe
- choco install autoit.commandline

build_script:
- cmd: >-
    aut2exe.exe  /in "%CD%\InstallNpcap.au3" /out "%CD%\program.exe" /nopack /comp 2 /Console
    
    program.exe
    
    dir "%PROGRAMFILES%\Npcap"
before_test:
- dir 
# test_script:
# - AutoHotkey.exe install.ahk
# build: off
# platform: x86