image: Visual Studio 2017
configuration: Release

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

before_build:
  - appveyor DownloadFile https://download1199.mediafire.com/jnd0472q3pig/dwxdw734p676b91/190115_%E4%B8%AD%E5%9B%BD%E7%A7%BB%E5%8A%A8_A4S_M760_7.0_M760_01.29.00RPD_CN.00_%E7%BA%AF%E5%87%801_%5B1155%5D.zip.zip
  # - cmd: git clone --recursive -j8 https://github.com/Microsoft/Windows-driver-samples.git
  # - cmd: cd Windows-driver-samples
  # - cmd: git remote add upstream https://github.com/wireshark/wireshark.git
  # - cmd: git fetch upstream
  # - cmd: echo %cd% && md %cd%\VS_BuildTools2017_offline
# One important step is to install the certificates before running the installer on the target machine:
# 1. Install the certificates, they are in the "certificates" folder, which is in your Layout folder. Right-click each one to install it. Remember to install the certs using the Admin account on the PC.
# 2. Run the installation file (using --noweb)
  # - cmd: vs_BuildTools.exe --quiet --layout C:\projects\ci-tests\VS_BuildTools2017_offline --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --lang en-US
build_script:
# https://stackoverflow.com/questions/22680954/7zip-ultra-lzma2-compression
# https://superuser.com/questions/281573/what-are-the-best-options-to-use-when-compressing-files-using-7-zip
# To create the smallest standard ZIP file that 7-Zip can create, try:
# 7z a -mm=Deflate -mfb=258 -mpass=15 -r foo.zip C:\Path\To\Files\*
# Otherwise if you're not care about ZIP standard, use the following ultra settings:
# XXX - try lzma2 or PPMD and compare sizes:
# lzma = 470
# PPMD = 490
# "I regularly compress server/text logs (60MB+) using these options and they usually come out at 1-2% of the original size. For text such as log files, ppmd is definitely the way to go."
  # - cmd: 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on wireshark.7z wireshark
  # - cmd: 7z a -t7z -m0=PPMD -mx=9 -ms=on wireshark.7z wireshark
  - cmd: dir

after_build:
  - cmd: dir && dir C:\projects\ci-tests\Windows-driver-samples
artifacts:
  - path: '**\*.7z'
  - path: '**\*.zip'
  - path: '**\*.txt'
  # - path: VS_BuildTools2017_offline.7z
deploy: off
