image: Visual Studio 2015

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

before_build:
  # - appveyor DownloadFile https://download.microsoft.com/download/5/A/8/5A8B8314-CA70-4225-9AF0-9E957C9771F7/vs_BuildTools.exe
  - cmd: git clone --recursive -j8 https://github.com/sgeto/Divert.git
  - cmd: cd Divert
  - ps: $env:PATH="${env:ProgramFiles(x86)}\Windows Kits\8.1\bin\x86;${env:PATH}"\
  - cmd: NMake2MSBuild.exe dirs /?
  - NMake2MSBuild.exe dirs
  - cmd: tree /F
  - cmd: git status
  - cmd: cd ..

build_script:
# https://stackoverflow.com/questions/22680954/7zip-ultra-lzma2-compression
# https://superuser.com/questions/281573/what-are-the-best-options-to-use-when-compressing-files-using-7-zip
# To create the smallest standard ZIP file that 7-Zip can create, try:
# 7z a -mm=Deflate -mfb=258 -mpass=15 -r foo.zip C:\Path\To\Files\*
# Otherwise if you're not care about ZIP standard, use the following ultra settings:
# XXX - try lzma2 or PPMD and compare sizes:
# lzma = 470
# PPMD = 490
# "I regularly compress server/text logs (60MB+) using these options and they usually come out at 1-2% of the original size. For text such as log files, ppmd is definitely the way to go."
  # - cmd: 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on wireshark.7z wireshark
  # - cmd: 7z a -t7z -m0=PPMD -mx=9 -ms=on wireshark.7z wireshark
  - cmd: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on Divert.7z Divert

after_build:
  - cmd: dir
artifacts:
  - path: '**\*.7z'
  - path: '**\*.zip'
  - path: Divert.7z
deploy: off