image: Visual Studio 2017
configuration: Release

skip_commits:
  files:
    - '**/*.md'
    - 'images/**/*.*'

before_build:
  - cmd: git clone --recursive -j8 https://github.com/sgeto/wireshark.git
  - cmd: cd wireshark
  - cmd: git remote add upstream https://github.com/wireshark/wireshark.git
  - cmd: git fetch upstream
  - cmd: cd ..
build_script:
# To create the smallest standard ZIP file that 7-Zip can create, try:
# 7z a -mm=Deflate -mfb=258 -mpass=15 -r foo.zip C:\Path\To\Files\*
# Otherwise if you're not care about ZIP standard, use the following ultra settings:
  - cmd: 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on wireshark.7z wireshark
after_build:
  - cmd: dir
artifacts:
  - path: '**\*.zip'
  - path: wireshark.zip
deploy: off